@startuml

start
if (gameWithBot) then (yes)
    :Player enter save button;
    :Player confirm save;
    if (confirm) then (yes)
        :Save game;
        :System save history of game state in database;
        stop
    else (no)
        :Player continues game; 
        stop
    endif
else (no)
    :Invalid action;
    stop

@enduml