@startuml

start
:Player enter surrender button;
:Player confirm surrender;
if (confirm) then (yes)
    :Player surrender;
    :System set loser as player;
else (no)
    :Player continues game; 
endif
stop

@enduml