@startuml

start

:Player enter start button;
:Player select game mode;
if (select mode) then (bot)
    :Player select difficulty;
    :Player start game with bot;
else (player)
    :Player waiting for another player;
    :Start game with another player;
endif
stop

@enduml