@startuml

skinparam actorStyle awesome
actor System as system

package SystemUseCases {
    usecase "Check End Game" as checkEndGame
    usecase "Check Win" as checkWin
    usecase "Check Draw" as checkDraw
    usecase "Check Lose" as checkLose
    usecase "Save history" as saveHistory
}

:system: --> checkEndGame

:system: --> checkWin
:system: --> checkLose

:system: --> checkDraw

:system: --> saveHistory

@enduml

